import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  fields: [
    defineField({ name: 'heroTitle', title: 'Hero Title', type: 'string', validation: Rule => Rule.required() }),
    defineField({ name: 'heroSubtitle', title: 'Hero Subtitle', type: 'string' }),
    defineField({ name: 'heroDescription', title: 'Hero Description', type: 'text', rows: 3 }),
    defineField({ name: 'heroImage', title: 'Hero Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'heroImageAlt', title: 'Hero Image Alternative Text', type: 'string' }),
    defineField({ name: 'vision', title: 'Vision', type: 'text', rows: 4, validation: Rule => Rule.required() }),
    defineField({
      name: 'mission',
      title: 'Mission Commitments',
      type: 'array',
      of: [{ type: 'string' }],
      validation: Rule => Rule.min(1).required(),
    }),
    defineField({
      name: 'coreValues',
      title: 'Core Values',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          defineField({ name: 'name', title: 'Name', type: 'string', validation: Rule => Rule.required() }),
          defineField({ name: 'description', title: 'Description', type: 'text', rows: 3 }),
        ],
        preview: { select: { title: 'name', subtitle: 'description' } },
      }],
      validation: Rule => Rule.min(1).required(),
    }),
    defineField({ name: 'history', title: 'History', type: 'array', of: [{ type: 'block' }], description: 'Rendered as the history timeline. Begin a paragraph with a year (e.g. "2004 — The Diocese of Baguio was formally established.") and the year appears as the milestone marker. Paragraphs without a leading year still appear, without a marker.', validation: Rule => Rule.required() }),
    defineField({
      name: 'leadership',
      title: 'Leadership & Administration',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          defineField({ name: 'name', title: 'Name', type: 'string', validation: Rule => Rule.required() }),
          defineField({ name: 'role', title: 'Role', type: 'string', validation: Rule => Rule.required() }),
          defineField({ name: 'photo', title: 'Photo', type: 'image', options: { hotspot: true } }),
        ],
        preview: { select: { title: 'name', subtitle: 'role', media: 'photo' } },
      }],
    }),
    defineField({ name: 'overviewHeading', title: 'Overview Heading', type: 'string', initialValue: 'One Catholic school community' }),
    defineField({ name: 'overviewNote', title: 'Statistics Note', type: 'string', initialValue: 'Counts are generated from currently published school records.' }),
    defineField({ name: 'valuesIntro', title: 'Core Values Intro', type: 'text', rows: 3, initialValue: 'The values that guide learning, leadership, service, and community life throughout the Diocese of Baguio Schools.' }),
    defineField({ name: 'historyHeading', title: 'History Section Heading', type: 'string', initialValue: 'A Heritage of Faith and Mission' }),
    defineField({ name: 'historyIntro', title: 'History Section Intro', type: 'text', rows: 3, initialValue: 'Rooted in the Cordillera and formed through generations of Catholic evangelization and education.' }),
    defineField({ name: 'structureHeading', title: 'Structure Section Heading', type: 'string', initialValue: 'Our Institutional Structure' }),
    defineField({ name: 'structureIntro', title: 'Structure Section Intro', type: 'text', rows: 3, initialValue: 'The Diocese provides pastoral direction, while the schools office supports coordination and each school serves its own educational community.' }),
    defineField({ name: 'ctaHeading', title: 'Closing Section Heading', type: 'string', initialValue: 'Discover our Catholic school community' }),
    defineField({ name: 'ctaText', title: 'Closing Section Text', type: 'text', rows: 3, initialValue: 'Find a school for your family or contact the Diocese of Baguio Schools office for assistance.' }),
    defineField({ name: 'purposeHeading', title: 'Purpose Section Heading', type: 'string', initialValue: 'Our Guiding Purpose' }),
    defineField({ name: 'overviewText', title: 'Overview Text', type: 'text', rows: 3, initialValue: 'The Diocese of Baguio Schools is the system of Catholic schools under the administration of the Diocese, serving families across Baguio City and the Province of Benguet. Its schools provide formation and learning from early childhood through secondary education.' }),
    defineField({ name: 'structureEyebrow', title: 'Structure Section Label', type: 'string', initialValue: 'How We Are Organized' }),
    defineField({ name: 'schoolsRoleText', title: 'Schools Role Text', type: 'text', rows: 3, initialValue: 'Each school responds to the needs of its local community while sharing a commitment to Gospel values, academic excellence, service, cultural respect, and responsible stewardship.' }),
    defineField({ name: 'leadershipHeading', title: 'Leadership Section Heading', type: 'string', initialValue: 'Leadership &amp; Administration' }),
    defineField({ name: 'browseButtonLabel', title: 'Browse Schools Button', type: 'string', initialValue: 'Browse Our Schools' }),
  ],
  preview: { prepare: () => ({ title: 'About Page' }) },
})
